development:
  adapter: postgresql
  encoding: unicode
  database: ember-tutorial_development
  host: localhost
<% if Gem.win_platform? %>
  username: ember-tutorial_development
  password: only_need_in_windows
<% end %>

test:
  adapter: postgresql
  encoding: unicode
  database: ember-tutorial_test
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: ember-tutorial_production
  host: localhost
